GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk3MzAyOTN9.g4IIGdZVojHghgDdEF98zFpcA13fyD5owP5YCdC7Mf8
Content-Type: application/json

###
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk3MzAyOTN9.g4IIGdZVojHghgDdEF98zFpcA13fyD5owP5YCdC7Mf8
Content-Type: application/json

{
  "name": "ball",
  "price": 5,
  "description": "a toy to throw around or play sports with",
  "image_url": "image.jpg"
}

###
PATCH http://localhost:3000/products/11.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk5ODQ1Njh9.eAPTbw-QSzQoFcP-C-Bg7LmoX1iXWK7M9vSK6AoJ2Is

{
  "price": 5
}

###
DELETE http://localhost:3000/products/9.json
Content-Type: application/json

###
GET http://localhost:3000/suppliers.json
Content-Type: application/json

###
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Test",
  "email": "iamanemail@test.com",
  "phone_number": "123-321-0000"
}

###
GET http://localhost:3000/suppliers/2.json

###
PATCH http://localhost:3000/suppliers/3.json
Content-Type: application/json

{
  "name": ""
}

###
DELETE http://localhost:3000/suppliers/2.json
Content-Type: application/json

### create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Jane",
  "email": "jane@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### login
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jess@test.com",
  "password": "password"
}

###
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk5ODQ0MTV9.wm-nWYrtUOQpLh36pMTlOpjJ_TnkVxP6MiQ_CoWqAAM
Content-Type: application/json

{
  "product_id": 7,
  "quantity": 2
}

### index
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk4OTM5MjR9.2_4jh2noS24ceziDb8JS-Xu8vKViCOfexp0UZr2otPM

###
GET http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk4OTM5MjR9.2_4jh2noS24ceziDb8JS-Xu8vKViCOfexp0UZr2otPM

###
POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2OTAyMzMyMDJ9.qVctuVaFlk50QURHguICjpaSU9NCwpsEcIbYMX0SPJ8
Content-Type: application/json

{
  "product_id": 5,
  "order_id": 2,
  "quantity": 10,
  "status": "carted"
}