GET http://localhost:3000/products.json
Content-Type: application/json

###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "description": "a fluffy, sometimes standoffish pet",
  "price": -25,
  "image_url": "https://media.istockphoto.com/id/91626487/photo/funny-kitten.jpg?s=612x612&w=0&k=20&c=9Ftu_rNQpfWhYkmQzvC2x_-yGKhoJmzUBemM4AlaWYw=" 
}

###
PATCH http://localhost:3000/products/11.json
Content-Type: application/json

{
  "price": -5
}

###
DELETE http://localhost:3000/products/9.json
Content-Type: application/json

###
GET http://localhost:3000/suppliers.json
Content-Type: application/json

###
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Amazon",
  "email": "iamanemail",
  "phone_number": "123-321-4201"
}

###
GET http://localhost:3000/suppliers/2.json

###
PATCH http://localhost:3000/suppliers/2.json
Content-Type: application/json

{
  "name": "test supplier"
}

###
DELETE http://localhost:3000/suppliers/2.json
Content-Type: application/json