json.name product.name
json.description product.description
json.price product.price
json.is_discounted? product.is_discounted?
json.tax product.tax
json.id product.id
json.supplier_id product.supplier_id
json.supplier product.supplier
json.images product.images
